on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"

tasks:
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_seai_monitoring_and_reporting
    params:
      url: s3://codema-dev/raw/2020_01_24_seai_monitoring_and_reporting_buildings_dublin.xlsx
    product: data/external/2020_01_24_seai_monitoring_and_reporting_buildings_dublin.xlsx
  
  - source: tasks.clean
    name: clean_mprns
    params:
      sheet_name: MPRN_data
      fuel_type: electricity
    product: data/interim/mprn.csv

  - source: tasks.clean
    name: clean_gprns
    params:
      sheet_name: GPRN_data
      fuel_type: gas
    product: data/interim/gprn.csv
    
  - source: tasks.merge_mprns_and_gprns
    product: data/interim/mprns_and_gprns.csv

  - source: tasks.pivot_to_one_column_per_year
    product: data/processed/seai_monitoring_and_reporting_buildings_dublin.csv