on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_buildings
    params:
      url: s3://codema-dev/2021_04_dublin_valuation_office.csv
    product: data/external/2021_04_dublin_valuation_office.csv
  - source: codema_dev_tasks.requests.fetch_file
    name: download_benchmarks
    params:
      url: s3://codema-dev/benchmarks.csv
    product: data/external/benchmarks.csv
  - source: codema_dev_tasks.requests.fetch_file
    name: download_benchmark_uses
    params:
      url: s3://codema-dev/benchmarks.zip
    product: data/external/benchmarks.zip
  - source: codema_dev_tasks.requests.fetch_file
    name: download_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg

  - source: tasks.convert_benchmark_uses_to_json
    product: data/interim/benchmark_uses.json
  - source: tasks.weather_adjust_benchmarks
    product: data/interim/weather_adjusted_benchmarks.csv

  - source: tasks.save_unknown_benchmark_uses
    product: data/interim/unknown_benchmark_uses.csv

  - source: tasks.apply_energy_benchmarks_to_floor_areas
    params:
      boiler_efficiency: 0.85
    product: data/processed/2021_04_dublin_valuation_office.csv

  - source: tasks.link_valuation_office_to_boundaries
    product: data/processed/2021_04_dublin_valuation_office_with_boundaries.csv
  
  # SAVE
  - source: tasks.save_building_columns
    name: save_electricity_demands
    params:
      columns: 
        - typical_electricity_kwh_per_m2y
        - electricity_demand_mwh_per_y
      filter_on_column: electricity_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_electricity_demands.csv

  - source: tasks.save_building_columns
    name: save_fossil_fuel_demands
    params:
      columns: 
        - typical_fossil_fuel_kwh_per_m2y
        - fossil_fuel_demand_mwh_per_y
      filter_on_column: fossil_fuel_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_fossil_fuel_demands.csv

  - source: tasks.save_building_columns
    name: save_building_energy_demands
    params:
      columns: 
        - typical_building_energy_kwh_per_m2y
        - building_energy_mwh_per_y
      filter_on_column: building_energy_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_building_energy_demands.csv

  - source: tasks.save_building_columns
    name: save_process_energy_demands
    params:
      columns: 
        - typical_process_energy_kwh_per_m2y
        - process_energy_mwh_per_y
      filter_on_column: process_energy_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_process_energy_demands.csv
  
  - source: tasks.save_building_columns
    name: save_electricity_heat_demands
    params:
      columns: 
        - typical_electricity_heat_kwh_per_m2y
        - electricity_heat_demand_mwh_per_y
      filter_on_column: electricity_heat_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_electricity_heat_demands.csv

  - source: tasks.save_building_columns
    name: save_fossil_fuel_heat_demands
    params:
      columns: 
        - typical_fossil_fuel_heat_kwh_per_m2y
        - fossil_fuel_heat_demand_mwh_per_y
      filter_on_column: fossil_fuel_heat_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_fossil_fuel_heat_demands.csv

  - source: tasks.save_building_columns
    name: save_industrial_low_temperature_heat_demands
    params:
      columns: 
        - typical_industrial_low_temperature_heat_kwh_per_m2y
        - industrial_low_temperature_heat_demand_mwh_per_y
      filter_on_column: industrial_low_temperature_heat_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_industrial_low_temperature_heat_demands.csv
  
  - source: tasks.save_building_columns
    name: save_industrial_high_temperature_heat_demands
    params:
      columns: 
        - typical_industrial_high_temperature_heat_kwh_per_m2y
        - industrial_high_temperature_heat_demand_mwh_per_y
      filter_on_column: industrial_high_temperature_heat_demand_mwh_per_y
    product: data/processed/2021_04_dublin_valuation_office_industrial_high_temperature_heat_demands.csv