tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_census_building_ages
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_10_06_ireland_census_individual_buildings_inferred_period_built.zip
    product: data/external/2021_10_06_ireland_census_individual_buildings_inferred_period_built.zip
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_small_area_ids
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_10_08_dublin_small_area_ids.csv
    product: data/external/2021_10_08_dublin_small_area_ids.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_small_area_electoral_district_id_map
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_10_08_small_area_electoral_district_id_map.json
    product: data/external/2021_10_08_small_area_electoral_district_id_map.json

  - source: tasks.download_building_energy_ratings
    product: data/external/BERPublicsearch.zip

  - source: tasks.unzip_building_energy_ratings
    product: data/external/BERPublicsearch

  - source: tasks.save_selected_columns_as_parquet
    params:
      names:
        SA_Code: small_area
        CountyName: countyname
        DwellingTypeDescr: dwelling_type
        Year_of_Construction: year_of_construction
        BerRating: energy_value
        TypeofRating: type_of_rating
        LivingAreaPercent: living_area_percent
        RoofArea: roof_area
        UValueRoof: roof_uvalue
        WallArea: wall_area
        UValueWall: wall_uvalue
        FloorArea: floor_area
        UValueFloor: floor_uvalue
        WindowArea: window_area
        UValueWindow: window_uvalue
        DoorArea: door_area
        UvalueDoor: door_uvalue
        GroundFloorArea: ground_floor_area
        FirstFloorArea: first_floor_area
        SecondFloorArea: second_floor_area
        ThirdFloorArea: third_floor_area
        GroundFloorHeight: ground_floor_height
        FirstFloorHeight: first_floor_height
        SecondFloorHeight: second_floor_height
        ThirdFloorHeight: third_floor_height
        MainSpaceHeatingFuel: main_sh_boiler_fuel
        SupplSHFuel: suppl_sh_boiler_fuel
        MainWaterHeatingFuel: main_hw_boiler_fuel
        SupplWHFuel: suppl_hw_boiler_fuel
        HSMainSystemEfficiency: main_sh_boiler_efficiency
        WHMainSystemEff: main_hw_boiler_efficiency
        HSEffAdjFactor: main_sh_boiler_efficiency_adjustment_factor
        WHEffAdjFactor: main_hw_boiler_efficiency_adjustment_factor
        HSSupplHeatFraction: suppl_sh_heat_fraction
        DeclaredLossFactor: declared_loss_factor
        ThermalBridgingFactor: thermal_bridging_factor
        NoOfSidesSheltered: number_of_sides_sheltered
        NoOfChimneys: number_of_chimneys
        NoOfOpenFlues: number_of_open_flues
        NoOfFansAndVents: number_of_fans
        NoOfFluelessGasFires: number_of_room_heaters
        DraftLobby: is_draught_lobby
        PermeabilityTestResult: permeability_test_result
        NoStoreys: number_of_storeys
        PercentageDraughtStripped: percentage_draught_stripped
        SuspendedWoodenFloor: is_floor_suspended
        StructureType: structure_type
        VentilationMethod: ventilation_method
        HeatExchangerEff: heat_exchanger_efficiency
        DeliveredLightingEnergy: lighting_demand
        DeliveredEnergyPumpsFans: pump_fan_demand
        DeliveredEnergyMainSpace: main_sh_demand
        DeliveredEnergySecondarySpace: suppl_sh_demand
        DeliveredEnergyMainWater: main_hw_demand
        DeliveredEnergySupplementaryWater: suppl_hw_demand
      dtypes:
        SA_Code: category
        CountyName: category
        DwellingTypeDescr: category
        Year_of_Construction: float32
        BerRating: float32
        TypeofRating: category
        LivingAreaPercent: float32
        RoofArea: float32
        UValueRoof: float32
        WallArea: float32
        UValueWall: float32
        FloorArea: float32
        UValueFloor: float32
        WindowArea: float32
        UValueWindow: float32
        DoorArea: float32
        UvalueDoor: float32
        GroundFloorArea: float32
        FirstFloorArea: float32
        SecondFloorArea: float32
        ThirdFloorArea: float32
        GroundFloorHeight: float32
        FirstFloorHeight: float32
        SecondFloorHeight: float32
        ThirdFloorHeight: float32
        MainSpaceHeatingFuel: category
        SupplSHFuel: category
        MainWaterHeatingFuel: category
        SupplWHFuel: category
        HSMainSystemEfficiency: float32
        WHMainSystemEff: float32
        HSEffAdjFactor: float32
        WHEffAdjFactor: float32
        HSSupplHeatFraction: float32
        DeclaredLossFactor: float32
        ThermalBridgingFactor: float32
        NoOfSidesSheltered: float32
        NoOfChimneys: float32
        NoOfOpenFlues: float32
        NoOfFansAndVents: float32
        NoOfFluelessGasFires: float32
        DraftLobby: category
        PermeabilityTestResult: float32
        NoStoreys: float32
        PercentageDraughtStripped: float32
        SuspendedWoodenFloor: category
        StructureType: category
        VentilationMethod: category
        HeatExchangerEff: float32
        DeliveredLightingEnergy: float32
        DeliveredEnergyPumpsFans: float32
        DeliveredEnergyMainSpace: float32
        DeliveredEnergySecondarySpace: float32
        DeliveredEnergyMainWater: float32
        DeliveredEnergySupplementaryWater: float32
    product: data/interim/selected_building_energy_rating_columns.parquet
  
  - source: tasks.extract_buildings_meeting_conditions
    product: data/interim/building_energy_ratings_meeting_conditions.parquet

  - source: tasks.extract_dublin_census_buildings
    product: data/interim/dublin_census_buildings.parquet

  - source: tasks.fill_census_with_bers
    product: data/interim/census_with_bers.parquet
  
  - source: tasks.create_archetypes
    product: data/processed/archetypes
  
  - source: tasks.fill_unknown_buildings_with_archetypes
    product: data/processed/unknown_buildings_filled_with_archetype
  
  - source: tasks.combine_known_and_archetyped_buildings
    product: data/processed/estimated_buildings.csv.gz